
output_hdf: "tcga.hdf"

timestamp: "2016_01_28" # This is the most recent timestamp

firehose_get_url: "http://gdac.broadinstitute.org/runs/code/firehose_get_latest.zip"

#cancer_types: ["ACC", "CESC", "COADREAD", #"FPPP", 
#               "HNSC", 
#               "KIRC", "LGG", "LUSC", "PAAD", "READ", "STAD", 
#               "THCA", "UCS", "BLCA", "CHOL", "DLBC", "GBM", 
#               "KICH", "KIRP", "LIHC", "MESO", "PCPG", "SARC", 
#               "STES", "THYM", "UVM", "BRCA", "COAD", "ESCA", 
#               "GBMLGG", "KIPAN", "LAML", "LUAD", "OV", "PRAD", 
#               "SKCM", "TGCT", "UCEC"]
cancer_types: ["HNSC", "BRCA", "GBM"]

# These flags identify nodes in the 
# Broad Firehose data processing DAG:
# http://gdac.broadinstitute.org/stddata-DAG.html
data_types:
#    Clinical_Pick_Tier1:          # Clinical data
#        run_type: "stddata"
#        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Clinical_Pick_Tier1.Level_4.{timestamp_abbr}00.0.0"
#        file_template: "{cancer_type}.clin.merged.picked.txt"
    Methylation_Preprocess:       # Methylation data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Methylation_Preprocess.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.meth.by_mean.data.txt"
    mRNAseq_Preprocess:           # mRNA-seq data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.mRNAseq_Preprocess.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.uncv2.mRNAseq_RSEM_normalized_log2.txt"
#    miRseq_Mature_Preprocess:     # mature miRNA data
#        run_type: "stddata"
#        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.miRseq_Mature_Preprocess.Level_3.{timestamp_abbr}00.0.0"
#        file_template: "{cancer_type}.miRseq_mature_RPM.txt" 
#    miRseq_Preprocess:            # miRNA data
#        run_type: "stddata"
#        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.miRseq_Preprocess.Level_3.{timestamp_abbr}00.0.0"
#        file_template: "{cancer_type}.miRseq_RPKM_log2.txt" 
    RPPA_AnnotateWithGene:        # RPPA proteomic data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.RPPA_AnnotateWithGene.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.rppa.txt"
    CopyNumber_Gistic2: # CNA data (with "noise" from germline CNVs removed)
        run_type: "analyses"
        zip_template: "analyses__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}-TP.CopyNumber_Gistic2.Level_4.{timestamp_abbr}00.0.0"
        file_template: "all_data_by_genes.txt"


exceptions:
    LAML: ["RPPA_AnnotateWithGene", "miRseq_Mature_Preprocess"]
    #BRCA: ["miRseq_Preprocess"]
